baseURL = "https://futingfei.github.io"
languageCode = "en-us"
title = "Fat Blog"
theme = "cactus"
googleAnalytics = "G-WLHHMZN550"


[params]
description = "想到啥写啥，内容主要包括区块链，科幻，美食等。"
mainSection = "posts"
showAllPostsOnHomePage = false # 是否展示所有 post，false默认展示 5 条
tagsOverview = false # 默认展示标签
showProjectsList = true
rss = true
colortheme = "white"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[[params.social]]
  name = "github"
  link = "https://github.com/futingfei"

[[params.social]]
  name = "email"
  link = "ftf15@foxmail"

[[params.social]]
  name = "weibo"
  link = "https://weibo.com/u/6568789575" 

[[params.social]]
  name = "rss"
  link = "https://tingfei.art/index.xml" 
